### ISSUE TITLE
[BUG] changing the name of a resource's organization manually

### ISSUE THREAD

**Issue by gepaltineanu** [code4romania/rvm-client#135]
Using the dsu admin:
Expected behavior: when editing a resource, to not be possible to modify the name of the organization to a name that is outside of the list of organization.
Actual behavior: it is possible to change the name of an organization manually to something that is not in the list and then save. This will render that resource un-editable and it will not be possible to delete it. For example the resource called “TestResource1” which can still be found in the list.

**Comment by RaduCStefanescu** [comment]
Thank you for the bug report @gepaltineanu 
We will have a look at this issue.

**Comment by robertardeleanu** [comment]
looking into it
